name: Deploy CRA TypeScript app to GitHub Pages

on:
  push:
    branches:
      - main   # main 브랜치 push시 실행 테스트

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. 빌드(Build) 실행
      - name: Build project
        run: npm run build

      # 5. GitHub Pages 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build   # CRA는 build 폴더
